---
title: "Lab 02 - Global plastic waste"
author: "Chunlin Chen, lexuan Huang, Yamin Wang, Shihan Zhou"
date: "`r Sys.Date()`"
output: html_document
---

### Load packages and data

```{r load-packages, message = FALSE, warning=FALSE}
library(tidyverse)
library(readxl)
```


## Load & join data sets

```{r load-data, message = FALSE}
# Member 2 (pair 1) write code to load File 1 data here:
data1 <- read_csv("data/mismanaged-plastic-waste-per-capita.csv")
plastic_data_all <- data1
plastic_data_all %>% head(n = 10)



# Member 4 (pair 2) write code to load File 2 data here:
data2 <- read_csv2("data/per-capita-ocean-plastic-waste.txt")
plastic_data_all <- data2 %>%
  select(-name) %>%
  left_join(plastic_data_all, by = "code")


# Member 1 (pair 1) write code to load File 3 data here:
data3 <- read_tsv("data/UN_country_population.tsv")
plastic_data_all <- data3 %>%
  select(-name) %>%
  right_join(plastic_data_all, by = "code")


# Member 3 (pair 2) write code to load File 4 data here:
data4 <- read_excel("data/UN_country_region.xlsx")
plastic_data_all <- data4 %>%
  select(-name) %>%
  right_join(plastic_data_all, by = "code")

```



```{r join-data, message = FALSE}
# Member 2 (pair 1) write code to create object 'plastic_data_all':




# Member 4 (pair 2) write code to join your data to 'plastic_data_all':




# Member 1 (pair 1) write code to join your data to 'plastic_data_all':




# Member 3 (pair 2) write code to join your data to 'plastic_data_all':



```


```{r print-data, message = FALSE}
# Member 2 (pair 1) adds code here to view the first 10 rows of 'plastic_data_all'



```



## Exercises

### Ex 1.

```{r Ex1, message = FALSE}
# Write your code here to answer exercise 1
region_frequency <- plastic_data_all %>%
  count(region, name = "number_of_coastal_countries") %>%
  arrange(desc(number_of_coastal_countries))

region_frequency

region_frequency %>%
  slice_max(
    order_by = number_of_coastal_countries,
    n = 1,
    with_ties = TRUE
  )



```



### Ex 2.

```{r Ex2, message = FALSE}
# Write your code here to answer exercise 2

# Calculate total mismanaged plastic waste for each country
plastic_data_all <- plastic_data_all %>%
  mutate(
    total_mismanage_plastic = mismanaged_plastic * population
  )

# Calculate the mean for each region
region_mean_plastic <- plastic_data_all %>%
  group_by(region) %>%
  summarise(
    mean_total_plastic = mean(
      total_mismanage_plastic,
      na.rm = TRUE
    ),
    .groups = "drop"
  ) %>%
  arrange(desc(mean_total_plastic))

region_mean_plastic

region_mean_plastic %>%
  slice_max(
    order_by = mean_total_plastic,
    n = 1,
    with_ties = TRUE
  )

region_mean_plastic %>%
  slice_min(
    order_by = mean_total_plastic,
    n = 1,
    with_ties = TRUE
  )



```
The region with the highest mean total mismanaged plastic waste is Asia  
The region with the lowest mean total mismanaged plastic waste is Oceania.

### Ex 3.

```{r Ex3, message = FALSE}
# Write your code here to answer exercise 3

plastic_data_all <- plastic_data_all %>%
  mutate(
    pct_mismanaged_plastic_ocean =
      mismanaged_plastic_ocean / mismanaged_plastic * 100
  )

region_median_pct <- plastic_data_all %>%
  group_by(region) %>%
  summarise(
    median_pct_ocean = median(pct_mismanaged_plastic_ocean),
    .groups = "drop"
  )

region_median_pct

plastic_data_all %>%
  filter(code == "SOM") %>%
  select(
    name,
    code,
    mismanaged_plastic,
    mismanaged_plastic_ocean,
    pct_mismanaged_plastic_ocean
  )

##NaN means “Not a Number”. The result is caused by Somalia, where bot
#mismanaged plastic variables are zero. Dividing zero by zero produces NaN.

plastic_data_clean <- plastic_data_all %>%
  drop_na(pct_mismanaged_plastic_ocean)

region_median_clean <- plastic_data_clean %>%
  group_by(region) %>%
  summarise(
    median_pct_ocean = median(pct_mismanaged_plastic_ocean),
    .groups = "drop"
  ) %>%
  arrange(median_pct_ocean)

region_median_clean

region_median_clean %>%
  slice_min(
    order_by = median_pct_ocean,
    n = 1,
    with_ties = TRUE
  )



```

### Ex 4.

```{r Ex4, message = FALSE}
# Write your code here to answer exercise 4

plastic_data_all <- plastic_data_all %>%
  rename(
    pop = population,
    mismanaged_pc = mismanaged_plastic,
    ocean_plastic_pc = mismanaged_plastic_ocean,
    total_mismanaged = total_mismanage_plastic,
    pct_ocean = pct_mismanaged_plastic_ocean
  )

plastic_data_all <- plastic_data_all %>%
  mutate(
    region = str_replace_all(
      region,
      "Latin America and The Caribbean",
      "LAC"
    )
  )

names(plastic_data_all)
unique(plastic_data_all$region)

region_summary <- plastic_data_all %>%
  group_by(region) %>%
  summarise(
    countries = n(),
    mean_mismanaged_pc = mean(mismanaged_pc, na.rm = TRUE),
    median_pct_ocean = median(pct_ocean, na.rm = TRUE),
    total_mismanaged_kg = sum(total_mismanaged, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  arrange(desc(total_mismanaged_kg))

region_summary


```
